name: wootasali
description: A new Flutter project for Show Notification Mapi Reports.

publish_to: 'android&iOS' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  photo_view: ^0.13.0
  flutter_statusbarcolor_ns: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/fgi.png"
  image_path_android: "assets/fgi.png"
  adaptive_icon_foreground: "assets/fgi.png"
  adaptive_icon_background: "#FBFBFB"

flutter_native_splash:
  background_image: "assets/splash.png"
  web: false

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: "Arabic Font"
      fonts:
        - asset: assets/fonts/arabic_font.ttf

    - family: "English Font"
      fonts:
        - asset: assets/fonts/english_font.ttf
